### PR TITLE
Improve capsule failures

### PR DESCRIPTION
**Pull request by jordelver**
This is for #386 

I've tried to handle missing data in Capsule CRM more elegantly. Errors are now thrown if the required data is missing and that is included in the email that the support team receive in the case of failed member creation so they know what to check for.

I've also added some more tests and tidied up a bit.

### CODE REVIEW

**Comment by jordelver** [comment]
Could someone (@pezholio or @pkqk) check this over, please? I'm pretty sure this is good. It's worked fine locally, but I'm [slightly concerned about this line](https://github.com/theodi/member-directory/commit/9af4895feddf5c1f2b5a99206df276050d5e376b#diff-718f0ff30d74bb13296b5c39e0c4db71R31) with existing data. Do you see any problems with this?

**Comment by pezholio** [comment]
I think this is fine - all members should have a product name (called Level on the Capsule side of things) and an email, so this should trickle down nicely :+1: 

Let me know if you're happy and I'll merge

**Comment by jordelver** [comment]
> all members should have a product name (called Level on the Capsule side of things) and an email, so this should trickle down nicely

Is this true? It was possible to create members in Capsule and have the details go into the member directory database without a `product_name` up until this PR :) I expect this doesn't affect most members though. Most will probably have a `product_name`.

I'm not sure there's an easy way to check this anyway, so we'll probably have to go for it?

**Comment by pezholio** [comment]
I think go for it. It's not destructive, the worst that will happen is @greenreveller gets some emails :smile:

**Comment by jordelver** [comment]
:+1: Let's do this

**Comment by greenreveller** [comment]
VERY GOOD PLAN :)
Have a great long weekend everyone!

**Pull request merged**
