### PR TITLE
Migrate to OAuth2

### PR DESCRIPTION
**Pull request by jordelver**
This is for #360 

Given the potential security implications of this change, could the code reviewer make sure to check that you can only login with an **@theodi.org** email address, please :smile:. It seems to work that way for me, but a second set of eyes would be good.

### CODE REVIEW

**Comment by pezholio** [comment]
I get a `redirect_uri_mismatch ` error this end :/

**Comment by pezholio** [comment]
No worries - I've fixed it.

Can we redirect to the `/members` page after login though? This is mainly for @greenreveller and the membership team to correct minor errors by navigating directly to the user's page - the Rails admin page is a bit intimidating for non techs

**Comment by jordelver** [comment]
Was it a code fix? 

> Can we redirect to the /members page after login though? 

Sure, I'll remove my change and it will got back to /members. I thought it made sense to go direct to the admin, but it's cool if that's not the intended use case :)

**Comment by pezholio** [comment]
Also, I can't login with a non-ODI address, but I get constantly redirected to a 'Choose an account' page. If that's something that's not configurable, it's fine and probably enough to dicourage non-ODI users.

**Comment by jordelver** [comment]
> Also, I can't login with a non-ODI address, but I get constantly redirected to a 'Choose an account' page. If that's something that's not configurable, it's fine and probably enough to dicourage non-ODI users.

What would the ideal case?

**Comment by pezholio** [comment]
> Was it a code fix?

Nah, I just generated some new keys - I'd set them up with an 'Other' application type

> What would the ideal case?

Ideal case would be redirecting to the homepage with an error, or just redirecting back to the site (so silently failing)

**Comment by jordelver** [comment]
> Ideal case would be redirecting to the homepage with an error, or just redirecting back to the site (so silently failing)

Ok, cool. I'll investigate.

**Comment by jordelver** [comment]
I don't think this is possible @pezholio. I can't see an option anywhere to specify an "error" URL and the redirect seems to all happen at Google's end.

I've removed the redirect.

**Comment by pezholio** [comment]
Fair enough - that's fine in that case :smile:

**Comment by pezholio** [comment]
Lemme set up some production keys and I'll merge this

**Comment by jordelver** [comment]
Great, thanks :+1:

**Comment by pezholio** [comment]
Sorry for the delay!

**Pull request merged**
