### PR TITLE
Fix problem where members are left in limbo

### LINKED ISSUE #445: Members getting trapped in Credit card payment system when they want to pay by invoice
As an employee of an organisation who is trying to sign up as a member I go through registration (and along the way I create a password for my organisation) until I reach payment page. At this point I realise have to pay by credit card. I don’t have a credit card to pay with so I contact the sales rep at the ODI to pay by invoice. 

I am sent a link by which to pay via invoice. When I click on this link and sign in again I am directed to the CC page. This is because I have already created a profile for myself on the member directory by setting up a password earlier. 
At this point the membership team and tech team need to delete my organisation and associated dependencies from Capsule and the member directory before I can use the invoice link to sign in. 

I don’t want to have to go through this confusion when I am signing up!

* [x] Fix problem where the member cannot complete the signup
* [ ] Add link to the invoice link from the payment page

### PR DESCRIPTION
**Pull request by jordelver**
This fixes #445 

The solution just forwards the member onto the thanks page so that the rest of the process can continue.

I'm not very happy with this solution, but it's probably the pragmatic one for now. What do you think @pezholio?

### CODE REVIEW

**Comment by jordelver** [comment]
I've got something else to add to this before merging :)

**Comment by jordelver** [comment]
OK @pezholio, this is good to go now. Thanks :+1:

**Comment by pezholio** [comment]
Yeah, I think this is the best flow unfortunately. The only alternative is to add a payment type option to the main form, but I think we wanted to encourage credit card payment wherever possible - @greenreveller what do you think?

**Comment by greenreveller** [comment]
Hi both, credit card payment is preferable but me and @jordelver decided we were going to add 'would you prefer to pay by invoice' option on the Supporter page so it's clear. Happy for that to go ahead.

Anything else you need me to look at on this?

**Comment by pezholio** [comment]
Nah, it's cool :)

**Pull request merged**
